sonar.projectKey=vzwingma_domotique-mobile
sonar.organization=vzwingma

sonar.sources=app,components,hooks
sonar.tests=app,components,hooks
sonar.test.inclusions=**/__tests__/**/*,**/*.test.ts,**/*.test.tsx,**/*-test.ts,**/*-test.tsx
sonar.exclusions=**/*.d.ts,**/coverage/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
